version: 0.01a


saliencyDetection:
      teacher:
            training:
                  file: trainTeacher.json
                  learning_rate: 0.0001
                  epochs: 120
                  batch_size: 100



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

