version: 0.24.308b


saliencyDetection:

      device: cpu

      teacher:
            training:
                  epochs:           12
                  batch_size:       16
                  batch_saving:     10
                  learning_rate:    0.001
                  loss_class:       BCELoss

                  files:
                        ModelSpatial:           horus_model_teacher_spatial.pt
                        ModelTemporal:          horus_model_teacher_temporal.pt
      
      student:
            training:
                  epochs:           12
                  batch_size:       16
                  batch_saving:     10
                  learning_rate:    0.0001

                  files:
                        ModelSpatial:                 horus_model_student_spatial.pt
                        ModelTemporal:                horus_model_student_temporal.pt

                        ModelSpatioTemporal:          horus_model_student_spatiotemporal.pt

                        



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

