version: 0.24.317b


saliencyDetection:

      device: cuda      #cpu | cuda

      teacher:
            training:
                  epochs:           24
                  batch_size:       32
                  batch_saving:     100
                  learning_rate:    0.0001
                  loss_class:       BCELoss

                  files:
                        ModelSpatial:           horus_model_teacher_spatial.pt
                        ModelTemporal:          horus_model_teacher_temporal.pt
      
      student:
            training:
                  epochs:           64
                  batch_size:       32
                  batch_saving:     100
                  learning_rate:    0.0001

                  files:
                        ModelSpatial:                 horus_model_student_spatial.pt
                        ModelTemporal:                horus_model_student_temporal.pt

                        ModelSpatioTemporal:          horus_model_student_spatiotemporal.pt

                        



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

