version: 0.01a


saliencyDetection:

      files:
            LossHistory:      loss_history.json
            Model:            horus_model.pt

      training:
            epochs:           12
            batch_size:       8
            batch_saving:      5

            teacher:
                  learning_rate:    0.0001
                  
      
            student:
                  learning_rate:    0.0001
                        



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

