version: 0.01a


saliencyDetection:
      training:
            learningRate: 0.0001
            epochs: 120


evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

