version: 0.02b


saliencyDetection:

      device: cpu

      teacher:
            training:
                  epochs:           12
                  batch_size:       8
                  batch_saving:     10
                  learning_rate:    0.001
                  loss_class:       CrossEntropyLoss

                  files:
                        LossHistorySpatial:     loss_history_teacher_spatial.json
                        LossHistoryTemporal:    loss_history_teacher_temporal.json
                        ModelSpatial:           horus_model_teacher_spatial.pt
                        ModelTemporal:          horus_model_teacher_temporal.pt
      
      student:
            training:
                  epochs:           12
                  batch_size:       8
                  batch_saving:     10
                  learning_rate:    0.0001

                  files:
                        LossHistorySpatial:           loss_history_student_spatial.json
                        LossHistoryTemporal:          loss_history_student_temporal.json
                        ModelSpatial:                 horus_model_student_spatial.pt
                        ModelTemporal:                horus_model_student_temporal.pt

                        LossHistorySpatioTemporal:    loss_history_student_spatiotemporal.json
                        ModelSpatioTemporal:          horus_model_student_spatiotemporal.pt

                        



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

