version: 0.01a


saliencyDetection:
      teacher:
            files: 
                  JSONFormat:       trainTeacher.json
                  Model:            horus_teacher_model.pt
            training:
                  learning_rate:    0.0001
                  epochs:           12
                  batch_size:       100



evaluation:
      baiases:
            - 0.7
            - 1
            - 0.9
            - 1

