testVersion: 0.1b


saliencyDetection:

      controllUnit:     False
      modelFileTeacher: horus_model_teacher_spatial.pt
      modelFileStudent: horus_model_student_spatial.pt
      modelUsages:
            teacherModel:     False
            studentModel:     False
      modelParameters:
            teacherModel:     True
            studentModel:     True
      predictionAccuracy:
            teacherModel:     False
            studentModel:     False
      trainSetExample:
            teacherModel:     False
            studentModel:     False
      validSetExample:
            teacherModel:     False
            studentModel:     False
      testSetExample:
            teacherModel:     False
            studentModel:     False
      plotDisplayer:
            teacherModel:     True
            studentModel:     True



collider:
      
      controllUnit:           False
      collisionTest:          False



